#!/bin/sh

# make a symbolic link to this file called ~/.zprofile
export TERMINAL="gnome-terminal"
export EDITOR="nvim"
export BROWSER="firefox"
export XDG_MUSIC_DIR="~/Music"
export PATH=$PATH:~/.local/bin
export PAGER="less"
# LOG="$HOME/profile-invocations"
# echo "-----" >>$LOG
# echo "Caller: $0" >>$LOG
# echo "TERMINAL: $TERMINAL" >>$LOG
# echo "EDITOR: $EDITOR" >>$LOG
# echo "BROWSER: $BROWSER" >>$LOG
# xset dpms 6000 6000 6000
# xset s 6000 6000
