#!/bin/sh

function notify {
    this=`basename $0`
    tmp_file=/tmp/${this//./-}.txt
    argument=""

    if [ -e $tmp_file ]; then
        last_id=`cat $tmp_file | sed 's/[^0-9]//g'`

        if [ -n "$last_id" ]; then
            argument="-r $last_id"
        fi
    fi

    notify-desktop $argument "$@" > $tmp_file
}

notifyMuted() {
	notify "Muted" -t 1500 --icon audio-volume-muted
}
notifyAudio() {
	volume=$(pulsemixer --get-volume | awk '{print $1}')
	if [ $volume -eq 0 ]; then
		notifyMuted
	elif [ $volume -le 30 ]; then
		notify "volume: $volume%" -t 1500 --icon audio-volume-low
	elif [ $volume -le 70 ]; then
		notify "volume: $volume%" -t 1500 --icon audio-volume-medium
	else
		notify "volume: $volume%" -t 1500 --icon audio-volume-high
	fi
}

case "$1" in
	muted)
		if [ $(pulsemixer --get-mute) -eq 0 ]
		then
			notifyAudio
			# notify "Unmuted" -t 1000 --icon audio-volume-high
			# echo unmuted
		else
			notifyMuted
			# echo muted
		fi
		;;
	audio)
		notifyAudio
		;;
		
	*)
		echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
		exit 2
esac
