#!/bin/sh
repo=$(ls ~/git_repos | dmenu)
succes=$?
echo $succes >> ~/scriptResult
if [ $succes -eq 0 ]
then
	# gnome-terminal --window --working-directory=$HOME/git_repos/$repo/build --window --working-directory=$HOME/git_repos/$repo/
	# gnome-terminal --working-directory=$HOME/git_repos/$repo/src
	$TERMINAL -d ~/git_repos/$repo/src
fi
