#!/bin/sh

while [ -n "$1" ]
do
	case "$1" in 
		-a) echo "option a used" 
			shift
			echo "Value is: $1"
			;;
		-b) echo "option b used" ;;
		*) echo "Option $1 is not an option" ;;
	esac
	shift
done
